export const SIGN_UP = "SIGN_UP"
export const LOG_IN =  "LOG_IN"
//export const RETURNING = "RETURNING"
//export const DELETE_USER = "DELETE_USER"
//export const EDIT_USER = "EDIT_USER"
//export const LOG_OUT = "LOG_OUT"